f = open('backend/src/routes/authRoute.ts', 'w', encoding='utf-8')
f.write("import { Router } from 'express'\n")
f.write("import { register, login, googleLogin, facebookLogin, getMe } from '../controllers/authController'\n")
f.write("import { protect } from '../middlewares/authMiddleware'\n")
f.write("\n")
f.write("const router = Router()\n")
f.write("\n")
f.write("router.post('/register', register)\n")
f.write("router.post('/login', login)\n")
f.write("router.post('/google', googleLogin)\n")
f.write("router.post('/facebook', facebookLogin)\n")
f.write("router.get('/me', protect, getMe)\n")
f.write("\n")
f.write("export default router\n")
f.close()
print('Done')
