#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
content = '''import { Request, Response } from 'express'
import bcrypt from 'bcryptjs'
import User from '../models/usersModel'
import { generateToken } from '../utils/jwt'

export const register = async (req: Request, res: Response) => {
    try {
        const { hoTen, taiKhoan, matKhau, email, sdt } = req.body

        const userExists = await User.findOne({ $or: [{ taiKhoan }, { email }] })
        if (userExists) {
            res.status(400).json({ message: 'Tai khoan hoac email da ton tai!' })
            return
        }

        const hashedPassword = await bcrypt.hash(matKhau, 10)

        const user = await User.create({
            hoTen,
            taiKhoan,
            matKhau: hashedPassword,
            email,
            sdt,
        })

        res.status(201).json({
            message: 'Dang ky thanh cong!',
            token: generateToken(user._id.toString(), user.vaiTro),
            user: {
                id: user._id,
                hoTen: user.hoTen,
                taiKhoan: user.taiKhoan,
                email: user.email,
                vaiTro: user.vaiTro,
            },
        })
    } catch (error) {
        console.error('[register] error:', error)
        res.status(500).json({ message: 'Loi server!', error: (error as Error).message })
    }
}

export const login = async (req: Request, res: Response) => {
    try {
        const { taiKhoan, matKhau } = req.body

        const user = await User.findOne({ taiKhoan })
        if (!user) {
            res.status(400).json({ message: 'Tai khoan khong ton tai!' })
            return
        }

        const isMatch = await bcrypt.compare(matKhau, user.matKhau!)
        if (!isMatch) {
            res.status(400).json({ message: 'Mat khau khong dung!' })
            return
        }

        res.json({
            message: 'Dang nhap thanh cong!',
            token: generateToken(user._id.toString(), user.vaiTro),
            user: {
                id: user._id,
                hoTen: user.hoTen,
                taiKhoan: user.taiKhoan,
                email: user.email,
                vaiTro: user.vaiTro,
            },
        })
    } catch (error) {
        console.error('[login] error:', error)
        res.status(500).json({ message: 'Loi server!', error: (error as Error).message })
    }
}

export const googleLogin = async (req: Request, res: Response) => {
    try {
        const { id_token } = req.body
        if (!id_token) {
            res.status(400).json({ message: 'Thieu id_token cua Google!' })
            return
        }

        const { OAuth2Client } = require('google-auth-library')
        const client = new OAuth2Client(process.env.GOOGLE_CLIENT_ID)
        const ticket = await client.verifyIdToken({
            idToken: id_token,
            audience: process.env.GOOGLE_CLIENT_ID,
        })
        const payload = ticket.getPayload()
        if (!payload or !payload.email) {
            res.status(400).json({ message: 'Token Google khong hop le!' })
            return
        }

        const googleId = payload.sub
        const email = payload.email
        const name = payload.name
        const picture = payload.picture

        let user = await User.findOne({ $or: [{ googleId }, { email }] })

        if (user) {
            if not user.googleId:
                user.googleId = googleId
                user.authProvider = 'local'
                await user.save()
        } else {
            const taiKhoan = 'google_' + (googleId ? googleId.substring(0, 8) : '')
            user = await User.create({
                hoTen: name || 'Google User',
                taiKhoan,
                email,
                anhDaiDien: picture || 'default.jpg',
                googleId,
                authProvider: 'google',
            })
        }

        res.json({
            message: 'Dang nhap Google thanh cong!',
            token: generateToken(user._id.toString(), user.vaiTro),
            user: {
                id: user._id,
                hoTen: user.hoTen,
                taiKhoan: user.taiKhoan,
                email: user.email,
                vaiTro: user.vaiTro,
                anhDaiDien: user.anhDaiDien,
            },
        })
    } catch (error) {
        console.error('[googleLogin] error:', error)
        res.status(500).json({ message: 'Loi xac thuc Google!', error: (error as Error).message })
    }
}
'''
# Hmm, this uses Python syntax not JS. Let me fix this approach.
print('Wrong approach, need JS syntax not Python')

# write_auth.py - generated by node
import os
print('script ready')
